project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ratings.urls',namespace='rate'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ratings/urls.py
from django.urls import path
from . import views
app_name='rating'
urlpatterns = [
    path('',views.photo_rate,name='rate'),
    path('rate/',views.rate_image,name='score'),
]

ratings/models.py
from django.db import models
from django.core.validators import MaxValueValidator,MinValueValidator
# Create your models here.
class rate(models.Model):
    phato = models.ImageField(upload_to='photo/')
    ratee = models.FloatField(default=0, validators=[MaxValueValidator(5),MinValueValidator(0)])
    def __str__(self):
        return str(self.pk)    
    class Meta:
        ordering=['pk']
    
    

ratings/views.py
from django.shortcuts import render
from .models import rate
from django.http import JsonResponse
# Create your views here.
def photo_rate(request):
    all=rate.objects.filter(ratee=0).order_by('?').first()
    return render(request,'ratings/main_page.html',{'all':all})
def rate_image(request):
    if request.method=='GET':
        pic_id=request.GET.get('pic_id')
        score=request.GET.get('pic_rate')
        object=rate.objects.get(id=pic_id)
        object.ratee=score
        object.save()
        return JsonResponse({'success':'true' , 'ratee':score},safe=False)
    return JsonResponse({'success':'false'})

ratings/templates/ratings/main_page.html
{% extends 'base.html' %}
{% block title %}
  rate now
{% endblock title %}
{% block content %}
  <div class="row">
      <div class="col text-center">
        <img src="{{all.phato.url}}" class="rounded" width="100%" alt="image to rate">
        <br>
        <a href="{% url 'rate:rate' %}"><button class="btn btn-primary mt-5" type="submit">next</button></a>
      </div>
        <div class="col text-center">
          <form action="" class="rate-form" method="GET" id="{{all.id}}">
            <button type="submit" class="fa fa-star fa-3x my-btn" id="1"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="2"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="3"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="4"></button>
            <button type="submit" class="fa fa-star fa-3x my-btn" id="5"></button>
          </form>
          <div id="connect-box"></div>
        </div>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- custom css & js -->
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="{% static 'main.js' %}" defer></script>

    <title>Rating site | {% block title %}{% endblock title %}</title>
  </head>
  <body>
    <div class="container mt-3">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>